### PR TITLE
new Paper and new smaller Solution

### PR DESCRIPTION
**Pull request by atraining**
I did link the main hompage. However, we could also use [YouTube](https://www.youtube.com/watch?v=KJC48LMvM2I) or the [Python SDK](https://github.com/konfuzio-ai/document-ai-python-sdk/).

### CODE REVIEW

**Comment by atraining** [comment]
In addition, I added a new paper which analyzes applications of document processing, i.e. Key Information Extraction, in legacy industries.

**Comment by tstanislawek** [comment]
@atraining Thanks for contributing to the repo, I have two comments:
1. If you want to add a new publication, please make sure if it's really good/important or at least publicly available (can you provide a link to the publication with the free access)? 
2. All companies are listed alphabetically, can you fix this?

**Comment by atraining** [comment]
@tstanislawek thansk for your feedback. I fixed the ordering, removed the paper I added recently as the journal does not offer any public access (sadly). However, I added a Paper by the SAP team.

**Comment by tstanislawek** [comment]
@atraining 
In the context of fixing ordering - OK
In the context of the new SAP paper: there is already a special section for the KIE task in which there is already the Chargrid: https://github.com/tstanislawek/awesome-document-understanding/blob/main/topics/kie/README.md#older

**Comment by atraining** [comment]
@tstanislawek Sorry I didn't see this. Probably, we made it now, even my contribution isn't that huge.

**Pull request merged**
